# Generated by Django 3.2 on 2022-04-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_auto_20220402_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='publication_date',
            new_name='pub_date',
        ),
    ]
